@NewKenyaAPI_HostAddress = http://localhost:5065

GET {{NewKenyaAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

### Seed Issues (Admin only)
POST {{host}}/api/issues/seed
Authorization: Bearer {{adminToken}}